version: '3.8'

services:
  goptl:
    build: ./
    command: ./wait-for-postgres.sh db ./goptl
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_HOST=crypto-platform
      - DB_PORT=5432
      - DB_NAME=crypto-platform
      - DB_USER=postgres
      - DB_PASSWORD=root

  goptldb:
    restart: always
    image: postgres:16.4-bookworm
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=crypto-platform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432

volumes:
  db_data:
