
services:
  app:
    image: test:latest
    container_name: test-app
    depends_on:
      - postgresql
    ports:
      - "8000:8080"
    networks:
      - ps

  postgresql:
    image: postgres:16.4-alpine3.20
    container_name: test-psql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: crypto-platform
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - ps
networks:
  ps:
    driver: bridge
