env: "dev"
dev:
  http_server:
    address: "0.0.0.0:8080"
    timeout: 4s
    idle_timeout: 60s

  database:
    host: postgresql
    port: 5432
    user: "postgres"
    password: root
    dbname: crypto-platform
    ssl_mode: "disable"