env: "local"
environments:
  local:
    http_server:
      address: "0.0.0.0:9032"
      timeout: 4s
      idle_timeout: 60s
    database:
      host: "localhost"
      port: 5432
      user: "postgres"
      password: root
      dbname: crypto-platform
      ssl_mode: "disable"

  dev:
    http_server:
      address: "0.0.0.0:4313"
      timeout: 4s
      idle_timeout: 60s
    database:
      host: "localhost"
      port: "5432"
      user: postgres
      password: root
      dbname: crypto-platform


